#ifndef _CONFIG_H
#define _CONFIG_H

#define PACKAGE_NAME  "@PROJECT_NAME@"
#define PACKAGE_VERSION "@CANTATA_VERSION_FULL@"
#define PACKAGE_STRING  PACKAGE_NAME" "PACKAGE_VERSION

#cmakedefine ENABLE_DEVICES_SUPPORT 1
#cmakedefine TAGLIB_FOUND 1
#cmakedefine COMPLEX_TAGLIB_FILENAME 1
#cmakedefine TAGLIB_EXTRAS_FOUND 1

#endif

