@SHARE_INSTALL_PREFIX@/cantata/config
@SHARE_INSTALL_PREFIX@/cantata/icons
@SHARE_INSTALL_PREFIX@/cantata/mpd
@SHARE_INSTALL_PREFIX@/cantata/scripts
@SHARE_INSTALL_PREFIX@/cantata/themes
@SHARE_INSTALL_PREFIX@/cantata/translations
@SHARE_INSTALL_PREFIX@/cantata
@CMAKE_INSTALL_PREFIX@/icons/ubuntu-mono-light/apps/22
@CMAKE_INSTALL_PREFIX@/icons/ubuntu-mono-light/apps
@CMAKE_INSTALL_PREFIX@/icons/ubuntu-mono-light
@CMAKE_INSTALL_PREFIX@/icons/ubuntu-mono-dark/apps/22
@CMAKE_INSTALL_PREFIX@/icons/ubuntu-mono-dark/apps
@CMAKE_INSTALL_PREFIX@/icons/ubuntu-mono-dark
@CMAKE_INSTALL_PREFIX@/lib/cantata
