######################################################################
# Automatically generated by qmake (2.01a) Fr Mai 25 19:04:58 2007
######################################################################

include("maia.pri")

TEMPLATE = lib #app
TARGET = 
CONFIG += staticlib

DEPENDPATH += .
INCLUDEPATH += .
QT -= gui
CONFIG += qt silent #debug

# Input

